language: r
cache:
  - packages
  - ccache

branches:
  only:
  - master

env:
  global:
    - RGL_USE_NULL=TRUE
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE

before_install:
 - wget 'http://downloads.sourceforge.net/project/sbml/libsbml/5.11.4/stable/libSBML-5.11.4-core-src.tar.gz?r=&ts=1435978044' -O /tmp/libsbml.tar.gz
 - tar -xf /tmp/libsbml.tar.gz
 - cd libsbml-5.11.4 && ./configure --prefix=/usr >/dev/null && sudo make install >/dev/null && cd .. && sudo rm -rf libsbml-5.11.4

r:
  - release
  - devel

bioc_packages:
  - rsbml